name: CheckStyle

on:
  pull_request:
    branches:
      - '**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run CheckStyle for specific module
        run: ./gradlew :ynoolee:check
        working-directory: ./
        continue-on-error: true

      - name: Run reviewdog
        if: always()
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: ynoolee/config/checkstyle.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
