name: CheckStyle

on:
  pull_request:
    branches:
      - '**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run CheckStyle for specific module
        run: ./gradlew :ynoolee:check
        working-directory: ./

      - name: Upload CheckStyle report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: checkstyle-report
          path: ynoolee/build/reports/checkstyle/
