name: CheckStyle

on:
  pull_request:
    branches:
      - '**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run CheckStyle for specific module
        run: ./gradlew :ynoolee:check
        working-directory: ./

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          pip3 install --user -U reviewdog
          reviewdog -reporter=github-pr-review -f=checkstyle -diff="git diff HEAD^" -fail-on-error -name="Module Checkstyle Results" -filter-mode=nofilter ynoolee/build/reports/checkstyle/main.xml ynoolee/build/reports/checkstyle/test.xml
